
# source: http://stackoverflow.com/questions/2758159/how-to-embed-a-python-interpreter-in-a-pyqt-widget

import sys, os, re
import traceback, platform
from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets
from electrum_smart import util

class Smartnode(QtWidgets.QWidget):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent)
        self.setupUi(self)

    def setupUi(self, SmartnodeList):
        SmartnodeList.setObjectName("SmartnodeList")
        SmartnodeList.resize(811, 457)
        SmartnodeList.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(SmartnodeList)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(SmartnodeList)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CreateButton = QtWidgets.QPushButton(self.widget)
        self.CreateButton.setObjectName("CreateButton")
        self.horizontalLayout.addWidget(self.CreateButton)
        self.EditButton = QtWidgets.QPushButton(self.widget)
        self.EditButton.setEnabled(False)
        self.EditButton.setObjectName("EditButton")
        self.horizontalLayout.addWidget(self.EditButton)
        self.RemoveButton = QtWidgets.QPushButton(self.widget)
        self.RemoveButton.setEnabled(False)
        self.RemoveButton.setObjectName("RemoveButton")
        self.horizontalLayout.addWidget(self.RemoveButton)
        self.ViewButton = QtWidgets.QPushButton(self.widget)
        self.ViewButton.setEnabled(False)
        self.ViewButton.setObjectName("ViewButton")
        self.horizontalLayout.addWidget(self.ViewButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget)
        self.tableWidgetMySmartnodes = QtWidgets.QTableWidget(SmartnodeList)
        self.tableWidgetMySmartnodes.setMinimumSize(QtCore.QSize(695, 0))
        self.tableWidgetMySmartnodes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetMySmartnodes.setAlternatingRowColors(True)
        self.tableWidgetMySmartnodes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetMySmartnodes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetMySmartnodes.setObjectName("tableWidgetMySmartnodes")
        self.tableWidgetMySmartnodes.setColumnCount(7)
        self.tableWidgetMySmartnodes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMySmartnodes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMySmartnodes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMySmartnodes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMySmartnodes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMySmartnodes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMySmartnodes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMySmartnodes.setHorizontalHeaderItem(6, item)
        self.tableWidgetMySmartnodes.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidgetMySmartnodes)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.startButton = QtWidgets.QPushButton(SmartnodeList)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_5.addWidget(self.startButton)
        self.startMissingButton = QtWidgets.QPushButton(SmartnodeList)
        self.startMissingButton.setObjectName("startMissingButton")
        self.horizontalLayout_5.addWidget(self.startMissingButton)
        self.UpdateButton = QtWidgets.QPushButton(SmartnodeList)
        self.UpdateButton.setObjectName("UpdateButton")
        self.horizontalLayout_5.addWidget(self.UpdateButton)
        self.autoupdate_label = QtWidgets.QLabel(SmartnodeList)
        self.autoupdate_label.setObjectName("autoupdate_label")
        self.horizontalLayout_5.addWidget(self.autoupdate_label)
        self.secondsLabel = QtWidgets.QLabel(SmartnodeList)
        self.secondsLabel.setObjectName("secondsLabel")
        self.horizontalLayout_5.addWidget(self.secondsLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(SmartnodeList)
        QtCore.QMetaObject.connectSlotsByName(SmartnodeList)

    def retranslateUi(self, SmartnodeList):
        _translate = QtCore.QCoreApplication.translate
        SmartnodeList.setWindowTitle(_translate("SmartnodeList", "Form"))
        self.CreateButton.setText(_translate("SmartnodeList", "Create Smartnode"))
        self.EditButton.setText(_translate("SmartnodeList", "Edit selected"))
        self.RemoveButton.setText(_translate("SmartnodeList", "Remove selected"))
        self.ViewButton.setText(_translate("SmartnodeList", "View selected"))
        self.tableWidgetMySmartnodes.setSortingEnabled(True)
        item = self.tableWidgetMySmartnodes.horizontalHeaderItem(0)
        item.setText(_translate("SmartnodeList", "Alias"))
        item = self.tableWidgetMySmartnodes.horizontalHeaderItem(1)
        item.setText(_translate("SmartnodeList", "Address"))
        item = self.tableWidgetMySmartnodes.horizontalHeaderItem(2)
        item.setText(_translate("SmartnodeList", "Protocol"))
        item = self.tableWidgetMySmartnodes.horizontalHeaderItem(3)
        item.setText(_translate("SmartnodeList", "Status"))
        item = self.tableWidgetMySmartnodes.horizontalHeaderItem(4)
        item.setText(_translate("SmartnodeList", "Active"))
        item = self.tableWidgetMySmartnodes.horizontalHeaderItem(5)
        item.setText(_translate("SmartnodeList", "Last Seen"))
        item = self.tableWidgetMySmartnodes.horizontalHeaderItem(6)
        item.setText(_translate("SmartnodeList", "Payee"))
        self.startButton.setText(_translate("SmartnodeList", "S&tart alias"))
        self.startMissingButton.setText(_translate("SmartnodeList", "Start &MISSING"))
        self.UpdateButton.setText(_translate("SmartnodeList", "&Update status"))
        self.autoupdate_label.setText(_translate("SmartnodeList", "Status will be updated automatically in (sec):"))
        self.secondsLabel.setText(_translate("SmartnodeList", "0"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    sys.exit(app.exec_())
